services:
  redis:
    image: redis:7
    container_name: app-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  app-api:
    container_name: app-api
    image: app-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      TZ: "America/Rio_Branco"
      REDIS_URL: redis://app-redis:6379/0
      UPLOAD_DIR: /shared_uploads
    volumes:
      - app_uploads:/shared_uploads
    depends_on:
      - redis
    restart: unless-stopped

  app-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "America/Rio_Branco"
      REDIS_URL: redis://app-redis:6379/0
      UPLOAD_DIR: /shared_uploads
    volumes:
      - app_uploads:/shared_uploads
    depends_on:
      - redis
    command: uv run python -m src.worker
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
      replicas: 3

volumes:
  redis_data:
  app_uploads:
